# Generated by Django 5.0 on 2024-10-29 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('physios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pain_level', models.IntegerField()),
                ('therapy_compliance', models.TextField()),
                ('soap_notes', models.TextField()),
                ('assessment_date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='patients.patient')),
                ('physio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='physios.physio')),
            ],
            options={
                'db_table': 'assessments',
            },
        ),
        migrations.CreateModel(
            name='ROMMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limb_type', models.CharField(max_length=20)),
                ('limb', models.CharField(max_length=55)),
                ('movement', models.CharField(max_length=50)),
                ('assessed_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expected_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rom_measurements', to='assessments.assessment')),
            ],
            options={
                'db_table': 'rom_measurements',
            },
        ),
    ]
