# Generated by Django 5.0 on 2024-11-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physio',
            old_name='address',
            new_name='qualifications',
        ),
        migrations.RemoveField(
            model_name='physio',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='physio',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='physio',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='physio',
            name='specialties',
        ),
        migrations.AddField(
            model_name='physio',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
    ]
