# Generated by Django 5.0 on 2024-11-15 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_therapysession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapysession',
            name='reminder_sent',
        ),
        migrations.AddField(
            model_name='therapysession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
