# Generated by Django 5.0 on 2024-11-15 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_therapysession_reminder_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapysession',
            options={'ordering': ['session_date']},
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='notes',
            field=models.TextField(default='No notes available'),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
