# Generated by Django 5.0 on 2024-11-20 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_therapysession_options_and_more'),
        ('physios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='physio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='physios.physio'),
        ),
        migrations.AlterField(
            model_name='personalnote',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_notes', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_sessions', to='patients.patient'),
        ),
    ]
